services:
  - type: web
    name: inspiranet-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /signin
        destination: /index.html
      - type: rewrite
        source: /signup
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /meeting
        destination: /index.html
      - type: rewrite
        source: /meeting/(.*)
        destination: /index.html
      - type: rewrite
        source: /privacy-policy
        destination: /index.html
      - type: rewrite
        source: /terms
        destination: /index.html
      - type: rewrite
        source: /cookie-policy
        destination: /index.html
      - type: rewrite
        source: /profile/(.*)
        destination: /index.html
      - type: rewrite
        source: /messages/(.*)
        destination: /index.html
      - type: rewrite
        source: /(.*)
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /icons/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.ico
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.png
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.jpg
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.jpeg
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
