console.log('🔧 Manual Token Clear Instructions:');
console.log('');
console.log('📱 In your browser:');
console.log('1. Press F12 to open Developer Tools');
console.log('2. Go to "Application" tab (or "Storage" in some browsers)');
console.log('3. Click on "Local Storage" on the left');
console.log('4. Right-click on your domain (localhost:8083)');
console.log('5. Select "Clear" or delete these items manually:');
console.log('   - authToken');
console.log('   - refreshToken');
console.log('   - userInfo');
console.log('');
console.log('6. Refresh the page (F5)');
console.log('7. You will be redirected to login page');
console.log('8. Login with: dhamodran17@gmail.com / Abcd123');
console.log('');
console.log('🎯 This will fix the 401 Unauthorized errors!');
console.log('✅ Posts will load properly after fresh login');
console.log('🔄 Scrolling will work on the homepage');

